from fastmcp import FastMCP
from typing import Dict, Any, Optional, List
import json
import asyncio
from pathlib import Path
import base64

# Initialize FastMCP server
mcp = FastMCP("DrawBot Compositional Design System")

# Store active design sessions
design_sessions: Dict[str, Dict[str, Any]] = {}


@mcp.tool
async def start_design_session(
    session_id: str = "default",
    width: int = 1000,
    height: int = 1000,
    description: str = ""
) -> Dict[str, Any]:
    """Start a new compositional design session with optional initial description."""
    design_sessions[session_id] = {
        "width": width,
        "height": height,
        "layers": [],
        "current_code": "",
        "history": [],
        "description": description
    }
    
    return {
        "session_id": session_id,
        "status": "created",
        "canvas": {"width": width, "height": height},
        "message": f"Design session '{session_id}' started with {width}x{height} canvas"
    }


@mcp.tool
async def add_layer(
    session_id: str = "default",
    layer_description: str = "",
    layer_type: str = "element"  # element, background, foreground, text, shape
) -> Dict[str, Any]:
    """Add a compositional layer to the design using natural language."""
    if session_id not in design_sessions:
        return {"error": f"Session '{session_id}' not found. Start a session first."}
    
    session = design_sessions[session_id]
    
    # Add layer to composition
    layer = {
        "type": layer_type,
        "description": layer_description,
        "code": "",  # Will be generated by sub-agent
        "order": len(session["layers"])
    }
    
    session["layers"].append(layer)
    
    return {
        "session_id": session_id,
        "layer_added": layer,
        "total_layers": len(session["layers"]),
        "message": f"Layer {len(session['layers'])} added: {layer_description}"
    }


@mcp.tool
async def modify_layer(
    session_id: str = "default",
    layer_index: int = -1,
    modification: str = ""
) -> Dict[str, Any]:
    """Modify an existing layer using natural language instructions."""
    if session_id not in design_sessions:
        return {"error": f"Session '{session_id}' not found"}
    
    session = design_sessions[session_id]
    
    if layer_index < 0 or layer_index >= len(session["layers"]):
        if layer_index == -1 and session["layers"]:
            layer_index = len(session["layers"]) - 1
        else:
            return {"error": f"Invalid layer index: {layer_index}"}
    
    # Update layer with modification
    layer = session["layers"][layer_index]
    layer["modifications"] = layer.get("modifications", [])
    layer["modifications"].append(modification)
    
    return {
        "session_id": session_id,
        "layer_index": layer_index,
        "modification": modification,
        "layer": layer,
        "message": f"Layer {layer_index} modified with: {modification}"
    }


@mcp.tool
async def compose_design(
    session_id: str = "default",
    style_hints: str = "",
    output_format: str = "png"
) -> Dict[str, Any]:
    """Compose all layers into final DrawBot code with optional style hints."""
    if session_id not in design_sessions:
        return {"error": f"Session '{session_id}' not found"}
    
    session = design_sessions[session_id]
    
    # This will be sent to the DrawBot sub-agent for code generation
    composition_request = {
        "canvas": {"width": session["width"], "height": session["height"]},
        "layers": session["layers"],
        "style_hints": style_hints,
        "output_format": output_format
    }
    
    # Store composition request for sub-agent
    session["composition_request"] = composition_request
    
    return {
        "session_id": session_id,
        "ready_for_generation": True,
        "composition": composition_request,
        "message": "Design composition ready for code generation"
    }


@mcp.tool
async def execute_drawbot_code(
    code: str,
    session_id: str = "default",
    output_name: str = "output.png",
    sandbox: str = "dagger"
) -> Dict[str, Any]:
    """Execute DrawBot code in sandboxed environment."""
    from sandbox.executor import execute_sandboxed
    
    # Execute in sandbox
    result = await execute_sandboxed(
        code=code,
        output_name=output_name,
        sandbox_type=sandbox
    )
    
    # Update session if exists
    if session_id in design_sessions:
        session = design_sessions[session_id]
        session["current_code"] = code
        session["history"].append({
            "code": code,
            "output": result.get("output_path"),
            "timestamp": result.get("timestamp")
        })
    
    return result


@mcp.tool
async def view_session(
    session_id: str = "default",
    include_code: bool = False
) -> Dict[str, Any]:
    """View current state of a design session."""
    if session_id not in design_sessions:
        return {"error": f"Session '{session_id}' not found"}
    
    session = design_sessions[session_id]
    
    response = {
        "session_id": session_id,
        "canvas": {"width": session["width"], "height": session["height"]},
        "layers": session["layers"],
        "layer_count": len(session["layers"]),
        "history_count": len(session["history"])
    }
    
    if include_code and session.get("current_code"):
        response["current_code"] = session["current_code"]
    
    return response


@mcp.tool
async def iterate_design(
    session_id: str = "default",
    feedback: str = "",
    specific_changes: str = ""
) -> Dict[str, Any]:
    """Iterate on existing design based on feedback."""
    if session_id not in design_sessions:
        return {"error": f"Session '{session_id}' not found"}
    
    session = design_sessions[session_id]
    
    # Store iteration request
    iteration = {
        "feedback": feedback,
        "specific_changes": specific_changes,
        "previous_code": session.get("current_code", "")
    }
    
    session["iterations"] = session.get("iterations", [])
    session["iterations"].append(iteration)
    
    return {
        "session_id": session_id,
        "iteration_number": len(session["iterations"]),
        "ready_for_revision": True,
        "message": "Design iteration recorded, ready for code revision"
    }


@mcp.tool
async def export_session(
    session_id: str = "default",
    include_history: bool = True
) -> Dict[str, Any]:
    """Export session data for saving or sharing."""
    if session_id not in design_sessions:
        return {"error": f"Session '{session_id}' not found"}
    
    session = design_sessions[session_id]
    
    export_data = {
        "session_id": session_id,
        "canvas": {"width": session["width"], "height": session["height"]},
        "layers": session["layers"],
        "current_code": session.get("current_code", "")
    }
    
    if include_history:
        export_data["history"] = session.get("history", [])
        export_data["iterations"] = session.get("iterations", [])
    
    return {
        "export": export_data,
        "message": f"Session '{session_id}' exported successfully"
    }


@mcp.tool
async def list_sessions() -> Dict[str, List[str]]:
    """List all active design sessions."""
    return {
        "sessions": list(design_sessions.keys()),
        "count": len(design_sessions)
    }


# Resources for DrawBot documentation and examples
@mcp.resource("drawbot://docs")
async def get_drawbot_docs() -> str:
    """Get DrawBot documentation for reference."""
    doc_path = Path(__file__).parent / "resources" / "drawbotdoc.md"
    if doc_path.exists():
        return doc_path.read_text()
    return "DrawBot documentation not found"


@mcp.resource("drawbot://examples/{example_type}")
async def get_examples(example_type: str) -> str:
    """Get example DrawBot code for various design patterns."""
    examples = {
        "grid": """# Grid layout example
db.newPage(1000, 1000)
db.fill(0.95)
db.rect(0, 0, db.width(), db.height())

cols, rows = 5, 5
margin = 50
gutter = 20

cell_width = (db.width() - 2 * margin - (cols - 1) * gutter) / cols
cell_height = (db.height() - 2 * margin - (rows - 1) * gutter) / rows

for row in range(rows):
    for col in range(cols):
        x = margin + col * (cell_width + gutter)
        y = margin + row * (cell_height + gutter)
        db.fill(0.2)
        db.rect(x, y, cell_width, cell_height)
""",
        "typography": """# Typography example
db.newPage(1000, 1000)
db.fill(1)
db.rect(0, 0, db.width(), db.height())

db.font("Helvetica", 72)
db.fill(0)
db.text("DrawBot", (db.width()/2, db.height()/2), align="center")
""",
        "shapes": """# Shapes example
db.newPage(1000, 1000)
db.fill(0.9)
db.rect(0, 0, db.width(), db.height())

# Circle
db.fill(1, 0, 0, 0.5)
db.oval(100, 100, 200, 200)

# Rectangle
db.fill(0, 1, 0, 0.5)
db.rect(400, 100, 200, 200)

# Polygon
db.fill(0, 0, 1, 0.5)
db.polygon((750, 100), (850, 200), (800, 300), (700, 300), (650, 200))
"""
    }
    
    return examples.get(example_type, "Example not found")


if __name__ == "__main__":
    mcp.run()